### ISSUE TITLE
Print the content of a json file in random order in a React component.

### ISSUE THREAD

**Issue by Parasgupta44** [Parasgupta44/ml-resources-react#32]
### Task
--------
Currently `Display.jsx` is printing the content of `ml_resources.json` in sequential manner. 
After the changes, the resources (items) should be displayed in a random manner (ofcourse once only).

Please check `Readme.md` and `Contributing.md` in the repo's root for more details.

**Comment by TheGLander** [comment]
Hello! I think I am done with this feature on my fork, can you assign me to this?

**Comment by Parasgupta44** [comment]
> Hello! I think I am done with this feature on my fork, can you assign me to this?

Sure, done!
