### ISSUE TITLE
Migrate React components from JavaScript to TypeScript.

### ISSUE THREAD

**Issue by Parasgupta44** [Parasgupta44/ml-resources-react#44]
## Task

Convert the React codebase from JavaScript to TypeScript. 
> There's only one major component `Display.jsx` to convert :)

Some things to consider while converting:
- Try to add interfaces / types wherever ( if ) needed.
- Assign the correct types to various elements in the components.

Please check `Readme.md` and `Contributing.md` in the repo's root for more details.

**Comment by zinovik** [comment]
@Parasgupta44 Hello, could you review my PR?
https://github.com/Parasgupta44/ml-resources-react/pull/45

**Comment by Parasgupta44** [comment]
Done. 
#45
