### ISSUE TITLE
Add a Footer to the Site

### ISSUE THREAD

**Issue by the-wrong-guy** [Parasgupta44/ml-resources-react#47]
There's is no footer in the website, can I add a footer to it?

**Comment by Parasgupta44** [comment]
> There's is no footer in the website, can I add a footer to it?

Sure @the-wrong-guy .
Thanks.

**Comment by the-wrong-guy** [comment]
@Parasgupta44 can you assign me to add the footer?

**Comment by Parasgupta44** [comment]
> can you assign me to add the footer?

Done !

**Comment by the-wrong-guy** [comment]
@Parasgupta44 Hey, there some CSS changes I like to make, like `setting root padding and margin to 0 `and `setting width and height of the body to 100%`.And there is **an error in which the entire site crash** when hovering on the cards and I `added keys` to each card since it was not present earlier and **was giving warning**

Please tell me if the footer is okay or you need some changes !! 

**Footer without setting margin and padding to zero**
![image](https://user-images.githubusercontent.com/52911853/96275148-07f48d80-0fef-11eb-87ee-58b7b3fcd381.png)

**Footer after setting margin and padding to 0**
![image](https://user-images.githubusercontent.com/52911853/96277444-e3e67b80-0ff1-11eb-8c53-5782aab710bc.png)


**Errors while hovering the cards**
![image](https://user-images.githubusercontent.com/52911853/96275510-720d3280-0fef-11eb-8277-1b97656dd8d3.png)

**Comment by Parasgupta44** [comment]
@the-wrong-guy Some points:
- The color of the footer can be changed ( to contrast with the bg color of site ).
- In the text, maybe just mention The `MIT License` only (along with copyright).

Also, can you do a PR with your changes, it will be easier for me to debug.
Thanks.

**Comment by the-wrong-guy** [comment]
@Parasgupta44 So you want only `MIT License ©️2020` cause I given a link to license file so the user can read it and should I make the CSS changes` *{ marign:0;  padding:0;}` or let me push the changes , and check whether it looks good or not, then I can further push changes if you want any

**Comment by Parasgupta44** [comment]
> MIT License ©️2020

Seems good.

> let me push the changes , and check whether it looks good or not, then I can further push changes if you want any

Sure..
